### ISSUE TITLE
Eclipse Gluon Plugin not working

### ISSUE THREAD

**Issue by adnion** [gluonhq/ide-plugins#1]
Hello gluonhq team!

You can't create a new Gluon project because the finish button is not working in Eclipse.
The problem is described here:
https://stackoverflow.com/questions/42953287/eclipse-gluon-new-project-does-not-finish

I asked on the eclipse buildship project here:
https://github.com/eclipse/buildship/issues/606

It would be great if you can provide your opinion regarding eclipse's behaviour and who could and should possibly fix this.

Thank you!

**Comment by tiainen** [comment]
Hi, we are aware of the issue and are currently doing a major revamp of the eclipse plugin.

In the meantime, a possible workaround as suggested in the stackoverflow thread, is to revert the buildship plugin to version 1.

**Comment by tiainen** [comment]
We've released version 2.5.0 of the Gluon plugin today which runs together with Buildship 2. You can install it through the Eclipse Marketplace or by using the following update site url: http://download.gluonhq.com/ideplugins/eclipse/e47/releases/2.x
