### ISSUE TITLE
Bugs in pom.xml for Gluon Mobile - Multi View Project (FXML) created by the Netbeans plugin 

### ISSUE THREAD

**Issue by gboeve** [gluonhq/ide-plugins#35]
The pom.xml created bij de new project 'Gluon Mobile - Multi View Project (FXML)' created by the Netbeans (12) contains the following  errors for the native android/ios build.
The tag:
                    <bundlesList>
                        <list>hellofx.hello</list>
                    </bundlesList>
results in the compile error "Can't find bundle for base name hellofx.hello, locale en_US"
The entry <list>hellofx.hello</list> must be removed.

The tags:
                    <reflectionList>
                        <list>javafx.fxml.FXMLLoader</list>
                        <list>com.gluonapplicationfxml.PrimaryPresenter</list>
                        <list>com.gluonapplicationfxml.SecondaryPresenter</list>
                        <list>javafx.scene.control.Button</list>
                        <list>javafx.scene.control.Label</list>
                    </reflectionList>
gives error "Could not resolve com.gluonapplicationfxml.PrimaryPresenter for reflection configuration. "
The tags should be changed to:
                    <reflectionList>
                        <list>javafx.fxml.FXMLLoader</list>
                        <list>com.gluonapplicationfxml.views.PrimaryPresenter</list>
                        <list>com.gluonapplicationfxml.views.SecondaryPresenter</list>
                        <list>javafx.scene.control.Button</list>
                        <list>javafx.scene.control.Label</list>
                    </reflectionList>

Same errors are also in the other Gluon Mobile projects.

**Comment by abhinayagarwal** [comment]
HI @gboeve ,

Thank you for reporting this issue. This is already been tracked internally and should be fixed in the next release of the plugin.
