### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by StardustProducts** [gluonhq/ide-plugins#41]
I don't see a single shred of documentation that says what this plugin is, what it does, or how to do it.  How about even just a link to SOMETHING?

**Comment by scientificware** [comment]
What are you looking for ? [Something like this ?](https://docs.gluonhq.com/#_user_interface_ui)

**Comment by abhinayagarwal** [comment]
Hi @StardustProducts ,

Please check this: https://docs.gluonhq.com/#_ide_plugins

I will add the link to the project's README.
