### ISSUE TITLE
IntelliJ Plugin generates incorrect project name in pom.xml

### ISSUE THREAD

**Issue by 12bPilot** [gluonhq/ide-plugins#45]
Possibly related to this: https://stackoverflow.com/questions/64598421/gluonmobile-multipleviewprojectwithglistenafterburner-will-not-build

Using the plugin (V2.8.5) to set up a project within IntelliJ, in the generated pom.xml, the project name gets an additional '>' character prefixed to the name. This of course leads to the very same build error as described in the link above.

Manually removing that character and subsequent build completes as expected.

**Comment by abhinayagarwal** [comment]
This issue has been fixed. You should be able to create to create new "Multi View Project with Glisten Afterburner" project without an additional '>' in the pom.xml.
